---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 785708357604683776-Tu9JExq5TcLVbgDEhGiN8J7OzdURFmO
:access_token_secret: 0WLbloSZOAind0ICv0MDBYVsp6AVQPpxKP81kSTPvsDvN
